### ISSUE TITLE
ModuleNotFoundError: No module named 'talib'

### ISSUE THREAD

**Issue by hungtrungthinh** [ZENALC/algobot#153]
Hello,

Ta-lib has been installed successfully, but run command algobot, it continues to report the error that tablib module cannot be found. Ta-lib and Talib are different??

Work well on macOS, but Windows 11 is not with "import talib ModuleNotFoundError: No module named 'talib'"

Thanks

**Comment by ZENALC** [comment]
ReadMe instructions have been updated for Windows; please revisit.
