### ISSUE TITLE
Algobot ideas

### ISSUE THREAD

**Issue by mecmen2** [ZENALC/algobot#16]
it will be nice f you to add a multi trailing function with 
candlestick tailing , fractal trailing, ATR trailing. 

And to also Breakdown the tailing into 
trailing stop
tailing start
tailing step

indicators
Fibo-zigzag and Gann zigzag.

Optimization function will make this tool a nuke

**Comment by ZENALC** [comment]
These are nice ideas. 

We are working on an optimizer and candlestick charts currently.

**Comment by Tabac12** [comment]
Can we also add an checkbox to disable margin inside the simulator and the real trader?

**Comment by ZENALC** [comment]
@Tabac12 Can you open an issue regarding this?

**Comment by danwalkeruk** [comment]
Are you already working on TA-Lib integration @ZENALC ?

**Comment by ZENALC** [comment]
@danwalkeruk It's in the backlog, but I haven't had the time yet...

**Comment by nzaar9** [comment]
Window to view list of telegram signals groups with an update button to download updated list

**Comment by apura4122** [comment]
Hi @ZENALC ,Can you given example of one more strategy e.g. highly used strategy like supertrend or bollinger band. I have been trying to integrate one but to no success.

**Comment by thangckt** [comment]
I have the same opinion as @apura4122
In addition, can you make a brief guide on how to set up and run the bot?
Thank

**Comment by ZENALC** [comment]
@thangckt visit the wiki for some guides

@apura4122 I'll add one soon

**Comment by ZENALC** [comment]
@thangckt @apura4122 Documentation regarding strategies will be added shortly. (within 2 hours of this posting).

Closing this issue. Please open new issues for new ideas. It'll be easier to keep track.
