### ISSUE TITLE
Algobot Issue

### ISSUE THREAD

**Issue by ipxs123** [ZENALC/algobot#28]
Hello, when i try use comamnd pip install -r requirements.txt i get error , he is asking update new version when new version is installed, wtf
![Untitled](https://user-images.githubusercontent.com/78660885/116398858-195bf500-a7dd-11eb-873f-9e5ce6eb70ba.png)

Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' so why directory is bad>?
(venv) C:\Users\atmos>python -m algobot
C:\Users\atmos\venv\Scripts\python.exe: No module named algobot

**Comment by ZENALC** [comment]
Have you cloned the project first? If not, you can also download the zip then make sure you `pip install requirements.txt` in the root of that folder.

**Comment by ZENALC** [comment]
Closing due to lack of response.
