### ISSUE TITLE
Call strategy

### ISSUE THREAD

**Issue by hall130** [ZENALC/algobot#40]
I wrote donchian channel strategy, How can I call through the GUI？ and where i should make some adjustments in the strategies class？

**Comment by hall130** [comment]
another question how i can adjust position, how to calculate the position?

**Comment by ZENALC** [comment]
Can you please elaborate?

All strategies should load automatically.

What do you mean by position? Do you mean trend?

**Comment by hall130** [comment]
> Can you please elaborate?
> 
> All strategies should load automatically.
> 
> What do you mean by position? Do you mean trend?
when i debuging example strategy, it's really work, but i see ever trade is buy all or sell all,This is very risky，maybe we need a way to manage positions. For example,I tried to write a donchian channel strategy, which is also a trend strategy, but there is a part of position management on it, not just buy all sell, this strategy will calculate the purchase position based on your current 
 free assets, which is a good method , Unfortunately I don’t know how to write code in the strategies, because, i don't know how to get the lowest price and highest price for period 55 or period 55 or period 55 and the current price

**Comment by hall130** [comment]
> Can you please elaborate?
> 
> All strategies should load automatically.
> 
> What do you mean by position? Do you mean trend?

the donchian channel will generate four positions, all the positions depend on your free assets, current price, the Average True Range, that's really nice, at this strategy, just provide your free assets' 2% ever trade, it's also trend strategy.

**Comment by ZENALC** [comment]
So basically, you mean don't go all in, but assign a portion of the portfolio?

**Comment by ZENALC** [comment]
One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now. 

We'll add support for % of assets soon, but this workaround should also work.

**Comment by hall130** [comment]
> One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> 
> We'll add support for % of assets soon, but this workaround should also work.

yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?

**Comment by hall130** [comment]
> > One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> > We'll add support for % of assets soon, but this workaround should also work.
> 
> yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?

i mean margin funds

**Comment by hall130** [comment]
if i want to add the donchian channel, at the UI, what i need to do ?

**Comment by ZENALC** [comment]
> > One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> > We'll add support for % of assets soon, but this workaround should also work.
> 
> yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?

Sure, so in that case, you can move funds you don't want to use from your margin account to your spot account.

As for the channel, you can add the values from the strategy to the dictionary that'll populate the graphs. You can view documentation on how to do that in the Wiki

**Comment by hall130** [comment]
> > > One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> > > We'll add support for % of assets soon, but this workaround should also work.
> > 
> > 
> > yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?
> 
> Sure, so in that case, you can move funds you don't want to use from your margin account to your spot account.
> 
> As for the channel, you can add the values from the strategy to the dictionary that'll populate the graphs. You can view documentation on how to do that in the Wiki

no yet, We need to unify, we are talking about future accounts, and this is work for futures?

**Comment by ZENALC** [comment]
> > > > One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> > > > We'll add support for % of assets soon, but this workaround should also work.
> > > 
> > > 
> > > yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?
> > 
> > 
> > Sure, so in that case, you can move funds you don't want to use from your margin account to your spot account.
> > As for the channel, you can add the values from the strategy to the dictionary that'll populate the graphs. You can view documentation on how to do that in the Wiki
> 
> no yet, We need to unify, we are talking about future accounts, and this is work for futures?

Unfortunately, we don't support futures at the moment.

**Comment by hall130** [comment]
> > > > > One way to do this right now, is by moving your funds from margin to non-margin and trading with what you have in margin right now.
> > > > > We'll add support for % of assets soon, but this workaround should also work.
> > > > 
> > > > 
> > > > yeah, if go all in, maybe will get an extremely bad result, example, loss your all funds, you know?
> > > 
> > > 
> > > Sure, so in that case, you can move funds you don't want to use from your margin account to your spot account.
> > > As for the channel, you can add the values from the strategy to the dictionary that'll populate the graphs. You can view documentation on how to do that in the Wiki
> > 
> > 
> > no yet, We need to unify, we are talking about future accounts, and this is work for futures?
> 
> Unfortunately, we don't support futures at the moment.

okay, It does not matter, i modify the file name of sample.py, it's not work, and where should I modify it next?

**Comment by ZENALC** [comment]
You have to modify the class name, not the file name.

So, in sample.py, change the strategy name to anything other than "Sample"

**Comment by hall130** [comment]
> You have to modify the class name, not the file name.
> 
> So, in sample.py, change the strategy name to anything other than "Sample"

ok, thanks, There is one last question, If I use donchian strategy, two types of signals will be generated, each of which has three types of position opening, stop loss, and clearance. How do you think I should control these signals to return to trade get the trade result?

**Comment by ZENALC** [comment]
Do you have Discord? Let's continue this conversation there. There's an invite link in the main page.

**Comment by hall130** [comment]
> 你有不和谐吗？让我们在那里继续这个对话。主页上有一个邀请链接。

i join the channel just recently

**Comment by ZENALC** [comment]
Will continue issue discussion there.
