### ISSUE TITLE
Documentation Request : How to create a new custom strategy from scratch

### ISSUE THREAD

**Issue by space-mvc** [ZENALC/algobot#90]
Hi can somebody create either an written documentation tutorial or video on:

"How to create a new strategy from scratch and run it via BackTesting"

and possibly another guide for

"How to use your new strategy for live trading" 

or is there a link to more documentation somewhere?

**Comment by ZENALC** [comment]
We have some documentation available here:

https://github.com/ZENALC/algobot/wiki

**Comment by ZENALC** [comment]
Closing because Algobot now has a built-in strategy builder. 

https://github.com/ZENALC/algobot/wiki/Strategies
