### ISSUE TITLE
No strategies found. Would you like to backtest a hold?

### ISSUE THREAD

**Issue by space-mvc** [ZENALC/algobot#91]
How to you fix this issue on the back testing page?
There seems to be no way to add or configure strategies

![x](https://user-images.githubusercontent.com/910208/129438821-f554023e-876f-458f-8c7b-98843fc1df7c.png)

**Comment by ZENALC** [comment]
Make sure you have some strategies selected

**Comment by fly2hi** [comment]
I am trying to test it and seems like no way to select a strategy even i am sure I created more than one!

**Comment by ZENALC** [comment]
@fly2hi configure your backtest and in the strategy, make sure it's enabled.

**Comment by ZENALC** [comment]
@PenguinDLL Thank you for providing help. @fly2hi feel free to open another issue if you're still having this error.
